feat: impl in oop del codice base, e aggiunta e gestione classifica
PeppeSa/qd-hanged-one pull request #7
Opened 2022-12-30 10:44 UTC by tommasodirosa

2022-12-30 12:39 UTC, TendTo requested changes

2022-12-30 12:39 UTC, TendTo commented on main.py
> +from src.classModules import *
Anche se così è più conciso, ti consiglierei di importare in maniera esplicita tutte le classi che ti interessano

2022-12-30 12:39 UTC, TendTo commented on src/functions.py
> +            flag = True
Non è necessario utilizzare una flag. Sarebbe più compatto un 'early return':

```py
# ...
lvl: int = 0
while True:
        lvl = int(input(_('\nScegli un livello di gioco:\n1. facile\n2. medio\n3. difficile\n\n')))
        if lvl == 1 or lvl == 2 or lvl == 3:
            return lvl
# ...
```

2022-12-30 12:39 UTC, TendTo commented on main.py
> +            hanged.startGame()
La riga `hanged.startGame()` è comune a tutti i casi, e potrebbe essere quindi posizionata dopo il match.

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccato.py
> +        while self.mistakesCounter != 6:
Anche se non ci dovesse essere alcun rischio, per scrupolo (e per rendere più esplicite le intenzioni) userei sempre 

```py
# ...
while self.mistakesCounter < 6:
# ...
```

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccato.py
> +                if self.word == ''.join(letter for letter in self.guessedLetters):
Non è sufficiente usare questa forma?

```py
# ...
if self.word == ''.join(self.guessedLetters):
# ...
```

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccato.py
> +    def __aggiorna_lettere_indovinate(self, parola, scelta, lettere_indovinate):
Mancano i tipi dei parametri della funzione

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccato.py
> +        print(' '.join(lettera for lettera in self.guessedLetters))
Non è sufficiente usare questa forma?

```py
# ...
print(' '.join(self.guessedLetters))
# ...
```

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccato.py
> +        f.close()
Quando si lavora con risorse che devono essere aperte e chiuse (come i file e gli stream) è sempre consigliabile utilizzare la struttura [with](https://www.programmareinpython.it/video-corso-python-intermedio/02-istruzione-with/).

```py
with open("src/classifica.txt", "a") as f:
        f.write(f"\n{self.nickname} ha vinto con {self.mistakesCounter} errori commessi.")
```

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccato.py
> +        yield life
Perché si utilizza la variabile life? Non sarebbe meglio fare direttamente lo `yield` della stringa?

2022-12-30 12:39 UTC, TendTo commented on src/classModules/impiccatoDifficile.py
> +        return random.choice(wordsList)
Dato che i tre metodi `__getWord` sono uguali a meno del path del file, avrebbe senso integrarli nella classe base e aggiungere il parametro path al metodo.

```py
# Nella classe 'Impiccato'
    def _getWord(self, file_path: str) -> str:
        wordsList: str = []  

        with open(file_path, 'r') as f:
            for line in f:
                word_ = line.rstrip('\n')
                wordsList.append(word_)

        return random.choice(wordsList) 

# Nelle sottoclassi
    def __init__(self, nickname: str) -> None:
        super().__init__(nickname)   
        self.word: str = self._getWord('src/db_words/parole_difficili.txt') # o i vari file in base alla sottoclasse
        self.guessedLetters: str = ["_" for letter in self.word]
```

2022-12-31 14:36 UTC, TendTo approved these changes

2023-03-08 18:00 UTC, PeppeSa approved these changes

2023-03-08 18:29 UTC, merged